#ifndef CUDA_ARP_CACHE_H
#define CUDA_ARP_CACHE_H

#include <cuda_runtime.h>   
#include <stdint.h>
#include "helper.h"
#include "ns3/log.h"
#include "ns3/cuda-net-device.h"

#define MAX_CACHE_SIZE 16 

namespace ns3{
    class CudaNetDevice;
    class CudaPacket;
    class CudaIpv4L3Protocol;
    class CudaIpv4Interface;
    class MACAddress;

    class CudaArpCache: public Managed{
        public:
            class Entry{
                public:
                    uint32_t ip; //!< IP address of the entry
                    MACAddress mac; //!< MAC address of the entry
                private:
                    /**
                     * \brief ARP cache entry states
                     */
                    enum ArpCacheEntryState_e
                    {
                        ALIVE,
                        WAIT_REPLY,
                        DEAD,
                        PERMANENT,
                        STATIC_AUTOGENERATED
                    };
                    ArpCacheEntryState_e m_state; //!< State of the entry
            };

            CudaArpCache();
            ~CudaArpCache();

            void SetDevice(CudaNetDevice* device, CudaIpv4Interface* interface);
            __host__ __device__ CudaNetDevice* GetDevice() const;
            __host__ __device__ CudaIpv4Interface* GetInterface() const;

            __host__ __device__ void AddEntry(uint32_t ip, MACAddress mac);
            __host__ __device__ void RemoveEntry(uint32_t ip);
            __host__ __device__ bool Lookup(uint32_t ip, MACAddress& mac) const;
            __host__ __device__ void Clear();

        private:
            CudaNetDevice* m_device; //!< Pointer to the associated NetDevice
            CudaIpv4Interface* m_interface; //!< Pointer to the associated Ipv4Interface
            Entry* m_entries; //!< Pointer to the array of ARP cache entries
            uint32_t m_entryCount; //!< Number of entries in the cache
    };
}
#endif